import localFont from "next/font/local";
import "./globals.css";
import Navbar2 from "./nopage/components/navbar2";
import Navbar1 from "./nopage/components/navbar1";
import Footer from "./nopage/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Kottin school",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <Navbar1 />
        <Navbar2 />
        <main className="flex-1">{children}</main> {/* Use flex-1 to allow main content to expand */}
        <Footer />
      </body>
    </html>
  );
}
